// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajuchomdtljkuhtmibti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqdWNob21kdGxqa3VodG1pYnRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MTU5NjEsImV4cCI6MjA2NzI5MTk2MX0.RLmdsgtUtcl94YvjbUncEc4MsFFNyXF12GD5-wK5fs0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});